### ISSUE TITLE
Open A11y Pilot: 4.2.2.1 assumes a python solution

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#10]
> The Contractor must conduct automated unit tests for all python based software modules. 

The existing solution may be python (CKAN at least), but no where else is Python demanded before.
Also "Python" since it's a language

**Comment by mgifford** [comment]
PHPUnit in is used in Drupal 8. Unit Testing in Drupal 7 was done with SimpleTest. So the tests for the Drupal pieces should be using PHPUnit. Makes sense that CKAN tests would be Python. Just useful to know what is being done.

**Comment by mgifford** [comment]
Oh ya, fixed the P. I'll see if I can insert Python somewhere else.

**Comment by nschonni** [comment]
Or remove it from the testing, since I'm not sure it makes sense to call it out there

**Comment by mgifford** [comment]
Ok, I nixed it from the testing line.
