### ISSUE TITLE
Open A11y Pilot: Is travel part of the 15K

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#12]
> - The presentation to a panel anticipated to be held in Shawinigan, Quebec in mid-March 2018. Reasonable expenses for attending the panel presentation will be covered, see Appendix 3 Section 4.1.2 for details.
> - The maximum funding available for Phase 1 of any contract resulting from this CFP is $15,000.00, applicable Taxes excluded.

The 15K is clear, and the travel expense rates/guides is clear, but whether one affects the other isn't (to me)

**Comment by mgifford** [comment]
Good point. I hope adding "The expenses associated with attending the panel are excluded from this cap." helps.
