### ISSUE TITLE
Open A11y Pilot: Remote presentation for Shawinigan

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#13]
Although travel is covered, will a remote attendance option be provided for those that prefer (or medically require it)

**Comment by mgifford** [comment]
I totally agree with that. Just from the carbon footprint, it would be great if everyone could participate remotely. 

I do wonder if there is one group that is calling in if they will have much of a chance to win. I'd think that the in-person presentations would be much more dynamic.
