### ISSUE TITLE
Open A11y Pilot: GitHub delivery

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#2]
> Under any contract resulting from the CFP, the Contractor will be required to deposit the Solution’s source code in a public facing repository on the GitHub platform - https://github.com - under an open source license as specified above.
>
> The Contractor must create and maintain a public repository for the project on GitHub during the period of the Contract. All updates to the Solution source code must be deposited on GitHub, as well as, the final Solution source code. This will enable anyone to subscribe to notifications of changes while also allowing for conversations, issue tracking, and code reviews.

- Who controls the the GitHub organization at the end, or is the repository ownership transfered to `canada-ca` or some other holding organization
- Is this intended to be "source open", ex: final work product is pushed as a single commit, or is work history also supposed to be included
- We also have stuff on BitBucket (CSE), maybe GitLab, and I'm sure SourceForge. Not sure if it needs to be restrictive here or not

**Comment by mgifford** [comment]
- It is a terrible run-on sentence but I added "Before the final payment, the ownership of the code should be transferred to https://github.com/canada-ca - this will enable anyone to subscribe to notifications of changes while also allowing for conversations, issue tracking, and code reviews."
- I think that including the work history should be included. Any ideas on how to make that more clear?
- I think it's fine to pick one for use for a particular implementation. Each RFP could call for a different repo if it works better for the agency building it. It really shouldn't be up to the Vendor to choose between them.
