### ISSUE TITLE
Open A11y Pilot: T&C reembersement

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#4]
> g. GC will not reimburse any person or entity for any cost incurred in participating in this consultative process;

Not sure if this contradicts the expenses bullets under the LOI part, or if this is supposed to be separate

**Comment by mgifford** [comment]
Agreed. It contradicts the CFP piece where there is compensation for travel. I've clarified that there is no compensation for replying to the LOI.
