### ISSUE TITLE
Open A11y Pilot: Dispute resolution w/o CEO

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#5]
> d. In the event the representatives of the Parties specified in Article 2.c. above are unable to resolve the dispute, it will be referred to the Participant's CEO and the PWGSC Assistant Deputy Minister, Acquisitions Branch who will have 10 Business Days to resolve the dispute.
>
> c. In the event the representatives of the Parties specified in Article 2.b. above are unable to resolve the dispute, it will be referred to the Participant's President and the PWGSC Director General, who will have 3 Business Days to resolve the dispute.
>
> d. In the event the representatives of the Parties specified in Article 2.c. above are unable to resolve the dispute, it will be referred to the Participant's CEO and the PWGSC Assistant Deputy Minister, Acquisitions Branch who will have 10 Business Days to resolve the dispute.

- What happens if the contractor is independent or the organization isn't setup with a CEO. EX: flat management
- Same issue about the "President"

**Comment by mgifford** [comment]
Good point. I think I moved all instances "to legal Signing Authority".
