### ISSUE TITLE
Open A11y Pilot: Response format

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#6]
> Please keep the length of your response to 3 - 8.5x11 pages, plus the signed copy of the Rules of Engagement Participation Agreement (as per Attachment 1). These can be provided as a PDF file to allow for analog signatures.

Similar to the format issue, size, spacing and font impact what "3 pages" represents, and may be documented somewhere at PSPC

**Comment by mgifford** [comment]
I think we could just say that it should be under 2500 words (which is actually 6 pages which I think they actually meant).
