### ISSUE TITLE
Open A11y Pilot Presentation formats

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#9]
> the presentation to include a Microsoft PowerPoint (.ppt) or Open Office Impress (.sxi) format and a demonstration of the prototype delivered to the Technical Authority.

- Format/copies delivered should be accessible like the Requirements formats
- There are online/offline presentation formats like ImpressJS that can also export to PDF and may be more accessible since they are delivered through a browser

**Comment by mgifford** [comment]
I'm not sure about ensuring that the presentation is accessible. I think its a good goal, but accessible to who? I guess folks looking at the archived presentation. This definitely will limit the types of presentations that are possible. 

I don't have a clear way forward on this.
